apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./infrastructure/beszel/repository.yaml
  - ./infrastructure/beszel/release.yaml
  - ./infrastructure/kustomization.yaml
