apiVersion: v1
kind: Service
metadata:
  name: beszel-hub-nodeport
  namespace: beszel
spec:
  type: NodePort
  selector:
    app: beszel-hub
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30890
