apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
  namespace: beszel
  labels:
    app: beszel-agent
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
      - name: agent
        image: henrygd/beszel-agent:latest
        env:
        - name: TOKEN
          value: "8267f84f-9c64-4a11-9d73-0411d4b85ac3"
        - name: HUB_URL
          value: "http://beszel-hub.beszel.svc.cluster.local:8090"
        ports:
        - containerPort: 45876
          hostPort: 45876
        volumeMounts:
        - name: host-root
          mountPath: /extra-filesystems/root
          readOnly: true
      volumes:
      - name: host-root
        hostPath:
          path: /
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
