apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdata
  namespace: netdata
  labels:
    app: netdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdata
  template:
    metadata:
      labels:
        app: netdata
    spec:
      containers:
      - name: netdata
        image: netdata/netdata:latest
        ports:
        - containerPort: 19999
        env:
        - name: NETDATA_CLAIM_TOKEN
          value: "XWD-q-Q0_vEcx7nI55v7gE00ygB_bzbqeqUMKkuftzBhBegbmW_DWUAsKPj9o9s1C0AAxtZqVBehJiWmae2DakuJveOu1KrOZANRR_RdWB9z-3MkJiClyLEXEYZqMWUvXGwclgI"   # Optional: set if you use Netdata Cloud
        - name: NETDATA_CLAIM_ROOMS
          value: "e1978bd8-2a45-4a2e-9e2c-b1547016ad73"
        securityContext:
          privileged: true   # Required for host system metrics
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys