apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netdata-db
  namespace: netdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi   # adjust as needed