apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel-hub
  namespace: beszel
  labels:
    app: beszel-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beszel-hub
  template:
    metadata:
      labels:
        app: beszel-hub
    spec:
      containers:
        - name: hub
          image: henrygd/beszel:latest
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: data
              mountPath: /beszel_data
          env:
            - name: PORT
              value: "8090"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: beszel-hub-data
